#!/usr/bin/env bash
set -euo pipefail
args=${*:-""}

if [[ -n "$args" ]]; then
  yarn run $args
  exit $?
fi

if ! command -v fzf >/dev/null 2>&1; then
  echo "fzf not found"
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found"
  exit 1
fi

if [ ! -f package.json ]; then
  echo "No package.json found"
  exit 1
fi

commands=$(jq -r ".scripts | keys[]" <package.json)

if workspaces=$(jq -r '.workspaces[]' <package.json 2>/dev/null); then
  for ws in $workspaces; do
    [[ ! -f "$ws/package.json" ]] && continue
    if ! scripts=$(jq -r ".scripts | keys[] | \"$ws \(.)\"" <"$ws/package.json" 2>/dev/null); then
      continue
    fi
    commands+=$(echo -e "\n$scripts")
  done
fi

# shellcheck disable=SC2016
if ! command=$(echo "$commands" | fzf --preview-window down:2 --preview '
set -- $(echo {}); ws=$1; script=$2;
[[ -z "$script" ]] && { script=$ws; ws="."; } || cwd=" --cwd $ws";
reset=$(tput sgr0);bold=$(tput bold);yellow=$(tput setaf 3);
echo -e "${yellow}${bold}yarn${cwd} run $script\n${reset}# $(jq -r ".scripts[\"$script\"]" <"$ws/package.json")"
'); then
  exit $?
fi

# shellcheck disable=SC2116,SC2046
set -- $(echo "$command")
ws=$1
script=${2:-''}
cwd=""

[[ -z "$script" ]] && script=$ws || cwd=" --cwd $ws"

echo "yarn${cwd} run $script"
# shellcheck disable=SC2086
yarn ${cwd} run "$script"
